//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Net.Cloudflare.FlareSolverr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvironmentalVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvironmentalVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Net.Cloudflare.FlareSolverr.Properties.EnvironmentalVariables", typeof(EnvironmentalVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSER_TIMEOUT.
        /// </summary>
        internal static string BrowserTimeout {
            get {
                return ResourceManager.GetString("BrowserTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADLESS.
        /// </summary>
        internal static string Headless {
            get {
                return ResourceManager.GetString("Headless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_HTML.
        /// </summary>
        internal static string LogHtml {
            get {
                return ResourceManager.GetString("LogHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG_LEVEL.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORT.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NODE_SKIP_PLATFORM_CHECK.
        /// </summary>
        internal static string SkipPlatformCheck {
            get {
                return ResourceManager.GetString("SkipPlatformCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST_URL.
        /// </summary>
        internal static string TestUrl {
            get {
                return ResourceManager.GetString("TestUrl", resourceCulture);
            }
        }
    }
}
