//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Net.Cloudflare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Net.Cloudflare.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge solver returned a failure response..
        /// </summary>
        internal static string ChallengeSolverFailed {
            get {
                return ResourceManager.GetString("ChallengeSolverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge solver threw an exception..
        /// </summary>
        internal static string ChallengeSolverThrewAnException {
            get {
                return ResourceManager.GetString("ChallengeSolverThrewAnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port {0}..
        /// </summary>
        internal static string FailedToConnectToFlareSolverrWithPort {
            get {
                return ResourceManager.GetString("FailedToConnectToFlareSolverrWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute FlareSolverr command..
        /// </summary>
        internal static string FailedToExecuteFlareSolverrCommand {
            get {
                return ResourceManager.GetString("FailedToExecuteFlareSolverrCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to solve Cloudflare IUAM challenge for {0}..
        /// </summary>
        internal static string FailedToSolveCloudflareIUAMChallengeWithUri {
            get {
                return ResourceManager.GetString("FailedToSolveCloudflareIUAMChallengeWithUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string FileNotFoundWithFilePath {
            get {
                return ResourceManager.GetString("FileNotFoundWithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find FlareSolverr executable..
        /// </summary>
        internal static string FlareSolverrExecutableNotFound {
            get {
                return ResourceManager.GetString("FlareSolverrExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlareSolverr returned a failure response: {0}.
        /// </summary>
        internal static string FlareSolverrReturnedAFailureResponseWithStatus {
            get {
                return ResourceManager.GetString("FlareSolverrReturnedAFailureResponseWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is not supported by this challenge solver..
        /// </summary>
        internal static string RequestMethodNotSupportedWithMethod {
            get {
                return ResourceManager.GetString("RequestMethodNotSupportedWithMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must be decorated with &apos;{0}&apos; in order to read the request stream..
        /// </summary>
        internal static string RequestMustBeDecoratedWithLazyUploadHttpWebRequestDecoratorWithTypeName {
            get {
                return ResourceManager.GetString("RequestMustBeDecoratedWithLazyUploadHttpWebRequestDecoratorWithTypeName", resourceCulture);
            }
        }
    }
}
