//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Net.Cloudflare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Net.Cloudflare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// https://stackoverflow.com/a/11389138
        ///function openNewBackgroundTab(uri) {
        ///    
        ///    var a = document.createElement(&quot;a&quot;);
        ///    var evt = document.createEvent(&quot;MouseEvents&quot;);
        ///
        ///    a.href = uri;
        ///    
        ///    //the tenth parameter of initMouseEvent sets ctrl key
        ///    evt.initMouseEvent(&quot;click&quot;, true, true, window, 0, 0, 0, 0, 0, true, false, false, false, 0, null);
        ///    
        ///    a.dispatchEvent(evt);
        ///
        ///}
        ///
        ///function heartbeat() {
        ///
        ///    // Let {PRODUCT_NAME} know that the tab is still open.
        ///    
        ///    fetc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebBrowserIUAMChallengeSolver {
            get {
                return ResourceManager.GetString("WebBrowserIUAMChallengeSolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{PRODUCT_NAME} - IUAM Challenge Solver&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin: 0; padding: 0;&quot;&gt;
        ///    &lt;div style=&quot;background-color: black; color: white; padding: 10px; text-align: center;&quot;&gt;
        ///        This webpage is being used by &lt;b&gt;{PRODUCT_NAME}&lt;/b&gt; to solve Cloudflare IUAM challenges in your web browser.
        ///        If you do not want to see this webpage, it can be disabled in your settings.
        ///    &lt;/div&gt;
        ///    &lt;div style=&quot;padding: 10px&quot;&gt;Waiting for challenges from  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebBrowserIUAMChallengeSolverWebpage {
            get {
                return ResourceManager.GetString("WebBrowserIUAMChallengeSolverWebpage", resourceCulture);
            }
        }
    }
}
